services:
  database:
    image: postgres
    restart: always
    container_name: db
    shm_size: 256mb
    ports:
      - "${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./../:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

volumes:
  db-data: