import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <header class="bg-transparent text-white">
          <div class="container mx-auto flex items-center justify-between p-4">
            <nav class="hidden md:flex space-x-6">
              <a href="#" class="hover:text-gray-300">
                Home
              </a>
              <a href="#" class="hover:text-gray-300">
                About
              </a>
              <a href="#" class="hover:text-gray-300">
                Services
              </a>
              <a href="#" class="hover:text-gray-300">
                Contact
              </a>
            </nav>

            <div class="md:hidden">
              <button class="text-white focus:outline-none">
                <svg
                  class="w-6 h-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M4 6h16M4 12h16m-7 6h7"
                  ></path>
                </svg>
              </button>
            </div>
          </div>
        </header>
        {children}
        <footer>test footer</footer>
      </body>
    </html>
  );
}
