import './globals.css';
import Header from '@/components/layout/header';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body cz-shortcut-listen="true">
        <Header />
        {children}
        <footer>test footer</footer>
      </body>
    </html>
  );
}
